name: Update releases.json

on:
  create:
  workflow_dispatch:

jobs:
  build:
    if: ${{ (startsWith(github.ref, 'refs/tags/')) || (github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Make checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Fetch `releases.json` and commit+push it
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/tarlepp/topo-successes/releases?per_page=100 > releases.json
          git config --global user.name "Tarmo Leppänen"
          git config --global user.email "tarlepp@users.noreply.github.com"
          git add releases.json
          git commit -a -m "Updated releases.json file content"
          git push origin HEAD:main